version: 2

project_name: cakd

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: cakd
    main: ./cmd/cakd
    binary: cakd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  github:
    owner: nguyentin05
    name: cakd-platform
  mode: keep-existing
  draft: false
