[[ if eq .Service.ProjectBuild "gradle-project" "gradle-project-kotlin" ]]
FROM gradle:jdk[[ if .Service.LanguageVersion ]][[ .Service.LanguageVersion ]][[ else ]]21[[ end ]] AS build
WORKDIR /app
COPY . .
RUN ./gradlew clean build -x test

FROM eclipse-temurin:[[ if .Service.LanguageVersion ]][[ .Service.LanguageVersion ]][[ else ]]21[[ end ]]-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
[[ else ]]
FROM maven:3.9-eclipse-temurin-[[ if .Service.LanguageVersion ]][[ .Service.LanguageVersion ]][[ else ]]21[[ end ]] AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:[[ if .Service.LanguageVersion ]][[ .Service.LanguageVersion ]][[ else ]]21[[ end ]]-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
[[ end ]]
