package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"text/template"
)

type InitializrMetadata struct {
	BootVersion struct {
		Values []ValueItem `json:"values"`
	} `json:"bootVersion"`
	JavaVersion struct {
		Values []ValueItem `json:"values"`
	} `json:"javaVersion"`
	Language struct {
		Values []ValueItem `json:"values"`
	} `json:"language"`
	Packaging struct {
		Values []ValueItem `json:"values"`
	} `json:"packaging"`
	Type struct {
		Values []ValueItem `json:"values"`
	} `json:"type"`
	Dependencies struct {
		Values []DependencyGroup `json:"values"`
	} `json:"dependencies"`
}

type ValueItem struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type DependencyGroup struct {
	Values []ValueItem `json:"values"`
}

const tpl = `// Code generated by registry-fetch. DO NOT EDIT.
package springboot

var ValidJavaVersions = []string{
{{- range .JavaVersions }}
	"{{ . }}",
{{- end }}
}

var ValidSpringBootVersions = []string{
{{- range .BootVersions }}
	"{{ . }}",
{{- end }}
}

var ValidProjectBuilds = []string{
{{- range .ProjectBuilds }}
	"{{ . }}",
{{- end }}
}

var ValidPackaging = []string{
{{- range .Packaging }}
	"{{ . }}",
{{- end }}
}

var ValidLanguages = []string{
{{- range .Languages }}
	"{{ . }}",
{{- end }}
}

var ValidSpringDependencies = []string{
{{- range .Dependencies }}
	"{{ . }}",
{{- end }}
}
`

type TemplateData struct {
	JavaVersions  []string
	BootVersions  []string
	ProjectBuilds []string
	Packaging     []string
	Languages     []string
	Dependencies  []string
}

func main() {
	body, err := fetchMetadata()
	if err != nil {
		log.Fatalf("Failed to fetch metadata: %v", err)
	}

	data, err := parseMetadata(body)
	if err != nil {
		log.Fatalf("Failed to parse metadata: %v", err)
	}

	if err := writeGeneratedFile(data); err != nil {
		log.Fatalf("Failed to write generated file: %v", err)
	}

	fmt.Println("Successfully generated internal/registry/services/springboot/versions_generated.go")
}

func fetchMetadata() ([]byte, error) {
	req, err := http.NewRequest("GET", "https://start.spring.io/metadata/client", nil)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status code: %d", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read body: %w", err)
	}

	return body, nil
}

func parseMetadata(body []byte) (TemplateData, error) {
	var meta InitializrMetadata
	if err := json.Unmarshal(body, &meta); err != nil {
		return TemplateData{}, fmt.Errorf("unmarshal: %w", err)
	}

	data := TemplateData{}

	for _, item := range meta.JavaVersion.Values {
		data.JavaVersions = append(data.JavaVersions, item.ID)
	}

	for _, item := range meta.BootVersion.Values {
		data.BootVersions = append(data.BootVersions, item.ID)
	}

	for _, item := range meta.Type.Values {
		data.ProjectBuilds = append(data.ProjectBuilds, item.ID)
	}

	for _, item := range meta.Packaging.Values {
		data.Packaging = append(data.Packaging, item.ID)
	}

	for _, item := range meta.Language.Values {
		data.Languages = append(data.Languages, item.ID)
	}

	for _, group := range meta.Dependencies.Values {
		for _, item := range group.Values {
			data.Dependencies = append(data.Dependencies, item.ID)
		}
	}

	return data, nil
}

func writeGeneratedFile(data TemplateData) error {
	t, err := template.New("registry").Parse(tpl)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format source: %w\n\n%s", err, buf.String())
	}

	err = os.WriteFile("internal/registry/services/springboot/versions_generated.go", formatted, 0600)
	if err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	return nil
}
