name: Test

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

permissions:
  contents: read

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./... -v -race -coverprofile=coverage.out

      - name: Upload coverage
        if: github.event_name == 'pull_request'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          fail_ci_if_error: false
